[package]
name = "reproit-sdk-rust-axum"
description = "Axum request capture adapter for the Repro It Rust SDK"
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
http-body = "=1.1.0"
reproit-core.workspace = true
reproit-sdk-rust = { path = "../reproit-sdk-rust", version = "=1.0.0" }
uuid = { workspace = true, features = ["v7"] }

[dev-dependencies]
serde.workspace = true
tokio.workspace = true
tower.workspace = true

[lints]
workspace = true
